### ISSUE TITLE
Generation de poi via une ligne

### ISSUE THREAD

**Issue by ravenfeld** [spfmoby/osm_nimrag#2]
Je viens de me rendre compte que ca pouvez être très moche en laissant
add-pois-to-lines

car tout les noeuds va créer un poi et du coup ca peut en faire beaucoup.

En changeant avec 

add-pois-to-lines: mid

c'est du coup qu'au milieu de la ligne, c'est peut etre pas le mieux mais pour ce que je cherche c'est moins foutoir.

**Comment by spfmoby** [comment]
C'est quoi qui est moche exactement ? tu as une image pour montrer de quoi tu parles ?

**Comment by spfmoby** [comment]
ok, je fais la modif.
Il ne doit pas y en avoir des masses des POI associés à des lignes non ? En tout cas pour l'instant je n'en ai vu aucun.

**Comment by ravenfeld** [comment]
Je ne l'avais pas vu avant, j'ai juste vu des lieu d'escalade pour le moment.
